#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAynHnpiFoudQXQMDJ8G7MxD/dHcJltopYCgyJmbowHJaG0a1RqusCSemFvWXztEPzp5IxUqnDgNMAwrgGey7YnDPnPSwpPzKqc6dIRecDRMtFZDgQkAbKKkjZKabqAd7uQGKKqo1QPQjvPf7JKpjIcmnn00pH8hW/lrU79FyaiisqaAXvjtPnMT+AyCHYIic0gYqyl5+D4pSnyh0jsIOf0BTGikaubcLVSYp1dn6XA8HMVhoYL7vLwGD+4bPxz6A16mBKLw6km0EYAUrZEetYqZ1av67oJ6oj8M/+0POfn6L5Zx6tkRnfwkZ8yn+E0ckdoRLQdPRMiUr27KZOiid1Vw== john.doe@nowhere.com

##
## executing a shell command during startup
##

coreos:
  units:
      - name: runcmd.service
        command: start
        content: |
          [Unit]
          Description=echo
          Requires=docker.service
          After=docker.service

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/docker run busybox /bin/sh -c "while true; do echo Hello World; sleep 1; done"
          
          [Install]
          WantedBy=multi-user.target          

write_files:
  - path: /home/core/.bashrc
    content: |
      . /usr/share/skel/.bashrc
      alias ll="ls -l"
