#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAynHnpiFoudQXQMDJ8G7MxD/dHcJltopYCgyJmbowHJaG0a1RqusCSemFvWXztEPzp5IxUqnDgNMAwrgGey7YnDPnPSwpPzKqc6dIRecDRMtFZDgQkAbKKkjZKabqAd7uQGKKqo1QPQjvPf7JKpjIcmnn00pH8hW/lrU79FyaiisqaAXvjtPnMT+AyCHYIic0gYqyl5+D4pSnyh0jsIOf0BTGikaubcLVSYp1dn6XA8HMVhoYL7vLwGD+4bPxz6A16mBKLw6km0EYAUrZEetYqZ1av67oJ6oj8M/+0POfn6L5Zx6tkRnfwkZ8yn+E0ckdoRLQdPRMiUr27KZOiid1Vw== john.doe@nowhere.com

##
## add second IP address by creating an aliased network interface
##

write_files:
  - path: /home/core/.bashrc
    content: |
      . /usr/share/skel/.bashrc
      alias ll="ls -l"

  - path: /etc/systemd/network/22-bridge0-settings.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      Name=en*

      [Network]
      DHCP=yes

      [Address]
      Label=en:0
      Address=192.168.1.245/24
      
coreos:
  units:
    - name: systemd-networkd.service
      command: restart
      